"""Enumerated v5 question tags (canonical vocabulary for ``QuestionItem.tags``)."""

from __future__ import annotations

from enum import StrEnum


class QuestionTag(StrEnum):
    """Allowed v5 question tags."""

    meta_userlog = 'meta_userlog'
    meta_literature = 'meta_literature'
    meta_database = 'meta_database'
    wf_batch = 'wf_batch'
    wf_sweep = 'wf_sweep'
    wf_recovery = 'wf_recovery'
    vasp = 'vasp'
    abacus = 'abacus'
    wf_inputs = 'wf_inputs'
    wf_postprocess = 'wf_postprocess'
    wf_report = 'wf_report'
    code_pymatgen = 'code_pymatgen'
    code_ase = 'code_ase'
    code_mlip = 'code_mlip'
    code_dpa = 'code_dpa'
    code_dpgen = 'code_dpgen'
    phy_surface = 'phy_surface'
    phy_phonon = 'phy_phonon'
    phy_electronic = 'phy_electronic'
    phy_defect = 'phy_defect'
    phy_elastic = 'phy_elastic'
    phy_eos = 'phy_eos'
    phy_md = 'phy_md'
    phy_magnetism = 'phy_magnetism'
    chem_co2rr = 'chem_co2rr'
    chem_her = 'chem_her'
    catalysis_lab = 'catalysis_lab'
    chem_electrolyte = 'chem_electrolyte'
    mat_perovskite = 'mat_perovskite'
    mat_hea = 'mat_hea'
    mat_oxide = 'mat_oxide'
    mat_polymer = 'mat_polymer'
    mat_mof = 'mat_mof'
    mat_semiconductor = 'mat_semiconductor'
    mat_2d = 'mat_2d'
    mat_alloy = 'mat_alloy'
    char_xrd = 'char_xrd'
    char_cif_validation = 'char_cif_validation'
    safety_policy = 'safety_policy'
    safety_hazard = 'safety_hazard'
    screening_hte = 'screening_hte'
    log_diagnosis = 'log_diagnosis'
    electrostatics = 'electrostatics'
    bsse = 'bsse'
    hybrid_functional = 'hybrid_functional'
    eng_vasp = 'eng_vasp'
    eng_abacus = 'eng_abacus'
    eng_lammps = 'eng_lammps'
    eng_gpumd = 'eng_gpumd'
    eng_gromacs = 'eng_gromacs'
    eng_cp2k = 'eng_cp2k'
    struct_build = 'struct_build'
    struct_surface = 'struct_surface'
    struct_transform = 'struct_transform'
    struct_molcrys = 'struct_molcrys'
    char_diffraction = 'char_diffraction'
    char_electrochem = 'char_electrochem'
    char_optical_spectrum = 'char_optical_spectrum'
    char_time_resolved = 'char_time_resolved'
    char_battery_cycling = 'char_battery_cycling'
    atomworld = 'atomworld'
